### ISSUE TITLE
Can see commands in help but they do not work

### ISSUE THREAD

**Issue by Ollymid** [jekyll/jekyll-compose#108]
I followed instruction commands and bundled so I have the jekyll-compose gem installed in my Gemfile
```yaml
source "https://rubygems.org"
ruby RUBY_VERSION

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll", "3.6.3"

# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima", "~> 2.0"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
   gem "jekyll-feed", "~> 0.6"
   gem "jekyll-paginate-v2", "~> 1.9"
   gem 'jekyll-compose', "~> 0.9"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

and I see the commands when I run `bundle exec Jekyll help`

However when I try to create a file for example `bundle exec jekyll post "My New Post"` or ` bundle exec jekyll draft "My new draft"`
 I get:
```bash
Configuration file: /Users/olly/Development/pop-website/_config.yml
jekyll 3.6.3 | Error:  no implicit conversion of nil into String
```
Am I missing something from my config or am I not entering the arguments correctly?

Perhaps I need a later version of Jekyll?

**Comment by DirtyF** [comment]
> Configuration file: /Users/olly/Development/pop-website/_config.yml
> jekyll 3.6.3 | Error:  no implicit conversion of nil into String

Check your _config file for errors.

**Comment by Ollymid** [comment]
Thanks for your reply @DirtyF 
I had reviewed my _config.yaml but couldn't see anything obvious?
```yaml
title: My Website
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: name
github_username:  name

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-compose
exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md

permalink: /pages/:year/:month/:day/:title/

future: true

pagination:
  enabled: true
  sort_reverse: true
  trail:
    before: 1
    after: 1
```
Any ideas?
