### ISSUE TITLE
Custom default front matter variables not working

### ISSUE THREAD

**Issue by Ollymid** [jekyll/jekyll-compose#109]
Hi there, sorry it's me again.

I am able to generate posts, pages, drafts etc with Jekyll-compose, however I cannot get the custom front matter variables that I put inside the jekyll_compose section of my config.yaml to appear in the front matter of any newly created posts/drafts

I have tried
```yaml
jekyll_compose:
  default_front_matter:
    drafts:
        main_img_url: "https://images-we-got-pop.imgix.net/website/blog/pop-logo-small.png"
        author_name: "Me"
        categories: "general"
        description: "Description"
    posts:
        main_img_url: "https://images-we-got-pop.imgix.net/website/blog/pop-logo-small.png"
        author_name: "Me"
        categories: "general"
        description: "Description"
```
and also without values:
```yaml
jekyll_compose:
  default_front_matter:
    drafts:
        main_img_url: 
        author_name: 
        categories: 
        description: 
    posts:
        main_img_url:
        author_name: 
        categories: 
        description: 
```
I have also tried to use the ones presented in the ReadMe but they did not appear in the front-matter either

But when I generate posts/drafts I only get the standard variables in my new post's front matter
```yaml
---
title: this-is-a-new-post
date: 2019-10-09 11:14 +0100
---
```
I have tried updating my Jekyll version from 3.7.0 to 3.8.6 but this issue still persists

Am I meant to run the jekyll-compose CLI commands with `--config` to use the custom variables or is this unrelated?
