### ISSUE TITLE
feat: generic compose command

### ISSUE THREAD

**Issue by DirtyF** [jekyll/jekyll-compose#84]
## Scenario

```
In order to manage my website content like a hacker
As a jekyll user using the jekyll-compose plugin
I can create all types of documents from the command line
```

## 
Replace current `draft` and `post` commands, with a generic `compose` subcommand, that could also handle collection documents.

### Creating 

`bundle exec jekyll compose _drafts/my-upcoming-post.md`
`bundle exec jekyll compose _post/new-release.md`
`bundle exec jekyll compose _recipes/yummy-cake.md`

```gherkin
Given I have a collection named _recipes
And that I have defined default front matter in config 
When I run `bundle exec jekyll compose _recipes/yummy-cake.md`
Then a new document with default front matter is created in the _recipes folder
```

### Publishing

`bundle exec jekyll publish _drafts/my-upcoming-post.md`
`bundle exec jekyll publish _post/new-release.md`
`bundle exec jekyll publish __recipes/yummy-cake.md`

### Unpublishing

`bundle exec jekyll unpublish _drafts/my-upcoming-post.md`
`bundle exec jekyll unpublish _post/new-release.md`
`bundle exec jekyll unpublish __recipes/yummy-cake.md`

## Front matter

Additional front-matter could be added in the `defaults:

```
defaults:
  -
    scope:
      path: ""
      type: "recipes" 
    values:
      layout: "recipe"
    front-matter:
      difficulty: ""
      time: ""
      ingredients: ""
```
